feat: hw13
kevin-glare/hardcode-dev-go pull request #12
Opened 2022-06-07 08:26 UTC by kevin-glare

2022-06-08 22:27 UTC, DmitriyVTitov requested changes
Неверно используются мьютексы. Это очень важно.

2022-06-08 22:27 UTC, DmitriyVTitov commented on hw13/pkg/api/api.go
> +	}
лучше использовать http.Error() чтобы клиент видел текст ошибки, а тут он только в консоль печатается

2022-06-08 22:27 UTC, DmitriyVTitov commented on hw13/pkg/api/docs.go
> +	mutex.Unlock()
Не, не так! :)
Мьютекс - это не магия, это просто булев флаг и всё!
Мьютекс создаётся прямо тут в функции и для каждого клиента он будет свой, а он должен быть общий.
То есть мьютекс - натурально простая булева переменная, только потокобезопасная.
То есть для нескольких горутин (а каждый обработчик запускается в горутине) нужно или сделать мьютекс глобальной переменной, или лучше добавить его в структуру API.

2022-06-12 09:31 UTC, DmitriyVTitov approved these changes
OK

2022-06-12 09:31 UTC, DmitriyVTitov commented on hw13/pkg/api/api.go
> +}
мьютекс объявляет перед защищаемыми полями структуры
если мьютекс защищает не все поля, то после защищаемых полей пишется пустая строка

2022-06-12 09:31 UTC, DmitriyVTitov commented on hw13/pkg/api/api.go
> +}
возникает вопрос: а какие поля тут защищает мьютекс? не понятно

2022-06-12 09:31 UTC, DmitriyVTitov commented on hw13/pkg/api/store.go
> +}
поскольку массив объявлен в этой структуре, то мьютекс логичнее объявить тут же:
```
type Store struct {
	index *hash.Index

        sync.Mutex
	Docs  []crawler.Document
}
```

2022-06-12 09:31 UTC, DmitriyVTitov commented on hw13/pkg/api/docs.go
> +func (api *Api) create(w http.ResponseWriter, r *http.Request) {
таких имён функций следует избегать: `create()` может означать что угодно

2022-06-12 09:31 UTC, DmitriyVTitov commented on hw13/pkg/api/docs.go
> +func (api *Api) read(w http.ResponseWriter, r *http.Request) {
`read` что?

2022-06-12 09:31 UTC, DmitriyVTitov commented on hw13/pkg/api/docs_test.go
> +func Test_create(t *testing.T) {
имена тестов не стандартные, рекомендую генерировать заглушки с помощью IDE
там будет что-то вреде `TestAPI_create()...`

2022-06-12 09:36 UTC, kevin-glare commented on hw13/pkg/api/docs.go
> +func (api *Api) create(w http.ResponseWriter, r *http.Request) {
он же лежит в docs
не опнимаю почему s.Docs.Create - это плохо? сразу же все понятно, что создаем документ
p.s. если честно привычка от контроллеров в rails...кажется что это самый чистый подход...тк s.Books.CreateBook - начинает казаться тавтологией

2022-06-12 09:38 UTC, kevin-glare commented on hw13/pkg/api/store.go
> +}
спасибо

2022-06-12 09:52 UTC, kevin-glare commented on hw13/pkg/api/api.go
> +}
хотел изначально так сделать, но подумал, что если добавится что-то еще кроме документов, придется делать отдельный мьютекс, а так вроде можно сделать один на апи

2022-06-12 09:57 UTC, merged